### ISSUE TITLE
Duplicate graphs on update

### ISSUE THREAD

**Issue by wouterdebruijn** [EasyH2O/EasyH2O-java#10]
When the updateCycle function is called, the jFrame where the graph is added to is not cleared first. This makes for a duplicate graph when the function is called again. 

Before calling `graphOutputJPanel.add(chartPanel);` call `graphOutputJPanel.removeAll();` first.

**Comment by wouterdebruijn** [comment]
![image](https://user-images.githubusercontent.com/24321650/104740138-dd2de880-5747-11eb-9340-ce936529db41.png)

**Comment by EmmaCharlotte** [comment]
Fixed it
